spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
---
mybatis:
  configuration:
    lazyLoadingEnabled: true
    aggressiveLazyLoading: false
    mapUnderscoreToCamelCase: true
---
spring:
  profiles: local
  task:
    fixedDelay: 1000
    name: localTask
  datasource:
    url: jdbc:oracle:thin:@114.31.122.90:1521:xe
    username: FINSET1
    password: FINSET1
  server:
    port: 8300
  scheduler:
    cron_1: 0 0/1 * * * *
    cron_2: 10 * 6 * * *
    cron_3: 0 0/1 6 * * *
  batch:
    initializer:
      enabled: false
    job:
      enabled: false
    table-prefix: FINSET1.BATCH_
  coocon:
#    apiUrl: http://localhost:8100/sol/gateway/
    apiUrl: https://sgw.coocon.co.kr/sol/gateway/
---
spring:
  profiles: dev
  task:
    fixedDelay: 5000
    name: devTask
  datasource:
    url: jdbc:oracle:thin:@10.30.50.12:1521:FSPDBD
    username: finsetdev
    password: finsetdev
  server:
    port: 8300
  scheduler:
    cron_1: 0 0 10 * * *
    cron_2: 0 0 11 * * *
    cron_3: 0 0 12 * * *
  batch:
    initializer:
      enabled: true
    job:
      enabled: false
    table-prefix: FINSET1.BATCH_
  coocon:
    apiUrl: http://localhost:8100/sol/gateway/
---
spring:
  profiles: real
  task:
    fixedDelay: 5000
    name: realTask
  datasource:
    url: jdbc:oracle:thin:@(DESCRIPTION=(FAIL_OVER=ON)(ADDRESS_LIST=(LOAD_BALANCE=ON)(ADDRESS=(PROTOCOL=TCP)(HOST=10.0.34.11)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=10.0.34.12)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=FSPDBM)))
    username: finset
    password: finset
  server:
    port: 8080
  scheduler:
    cron_1: 0/30 * * * * *
    cron_2: 10 * * * * *
    cron_3: 0 0/1 * * * *
  batch:
    initializer:
      enabled: false
    job:
      enabled: false
  coocon:
    apiUrl: http://localhost:8100/sol/gateway/
    